### ISSUE TITLE
Can't see graph at all

### ISSUE THREAD

**Issue by paulo27ms** [KiameV/rimworld-changeskilllevel#1]
Is it possible to put the graph below the other options instead to the side?
For some reason my mod options has the scroll bar in the middle of the screen (UI 1x, 1366x768) and I can click the option but the graph is completely blocked.
Not a huge deal but would make balancing somewhat easier.
Thanks for the mod by the way, Mad Skills had some bugs with some skills for me, this is much better.

**Comment by KiameV** [comment]
Eww that's an oversight on my part. Fixed with version 1.0.1.2

Thanks for reporting this issue!
